# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Build App'

# - script: |
#     CI=true npm run test
#   displayName: 'Run tests'
#   condition: "succeeded()"

- script: |
    git config --global user.email $(GitHub.Email)
    git config --global user.name $(GitHub.Name)
  displayName: "Config git credentials"
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"


- script: |
    node deploy.js $(Github.UserName) $(GitHub.AccessToken)
  displayName: 'Deploy App to GitHub Pages'
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
